<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
      <PackageReference Include="WolverineFx.FluentValidation" Version="6.39.1" />
      <PackageReference Include="WolverineFx.Http" Version="6.39.1" />
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

</Project>
