<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ExpenseTrackerWorker-c1354626-62ee-4d92-92bd-6170369e8b54</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire" Version="1.8.25" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="Quartz" Version="4.1.1" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="WolverineFx.FluentValidation" Version="6.40.0" />
        <PackageReference Include="WolverineFx.Http" Version="6.40.0" />
    </ItemGroup>
</Project>
